server:
  port: 8080
spring:
  application:
    name: shiro_name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_jwt?serverTimezone=UTC
    username: root
    password: sxn700320
  redis:
    host: localhost
    port: 6379
    database: 0
logging:
  level:
    org.springframework.web: debug
    camellia.prebookingshiro: debug